application: poketweet
version: v1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: Flask
  version: 0.11.1
- name: Jinja2
  version: 2.8
- name: MarkupSafe
  version: 0.23
- name: Werkzeug
  version: 0.11.10
- name: configargparse
  version: 0.10.0
- name: click
  version: 6.6
- name: itsdangerous
  version: 0.24
- name: peewee
  version: 2.8.1
- name: wsgiref
  version: 0.1.2
- name: geopy
  version: 1.11.0
- name: protobuf
  version: 2.6.1
- name: requests
  version: 2.10.0
- name: s2sphere
  version: 0.2.4
- name: gpsoauth
  version: 0.3.0
- name: protobuf-to-dict
  version: 0.1.0
- name: PyMySQL
  version: 0.7.5
- name: flask-cors
  version: 2.1.2
- name: flask-compress
  version: 1.3.0
- name: tweepy
  version: 3.5.0
- name: bs4
  version: 0.0.1
